name: E2E tests + Monitor

on:
  push:
  schedule:
    - cron: '0 */4 * * *' # Every 4 hours

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      working-directory: ./e2e-monitor
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install
        working-directory: ${{env.working-directory}}
        run: npm install
      - name: Test
        working-directory: ${{env.working-directory}}
        run: npm test
