name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  npm:
    name: NPM Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Replace dependencies
        run: |
          # Allow public static pages in npm package
          echo "" > .gitignore
          # Leave only runtime dependencies
          ./replace-dependencies.js
      - name: Publish
        run: |
          export NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
          npm publish
